spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:8083
    consumer:
      group-id: library-group
      auto-offset-reset: earliest
      topic: library-consumer-topic
    producer:
      topic: library-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
